spring:
  profiles:
    active: dev
  application:
    name: wechat-mall-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://192.168.100.101:3307/wechat_mall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource